-- Cómo podemos saber cuántos estudiantes nuevos tenemos por suscripción semana a semana y mes por mes
-- Semana a Semana
SELECT
    T2.WEEK
    ,COUNT(DISTINCT T1.ID_STUDENT) AS CANT_STUDENTS
FROM 
    DWH.FACT_SUBSCRIPTION T1
    INNER JOIN DWH.DIM_DATE T2 ON T1.ID_DATE = T2.ID_DATE
WHERE 1=1
GROUP BY 1;

-- Mes a Mes
SELECT
    T2.MONTH
    ,COUNT(DISTINCT T1.ID_STUDENT) AS CANT_STUDENTS
FROM 
    DWH.FACT_SUBSCRIPTION T1
    INNER JOIN DWH.DIM_DATE T2 ON T1.ID_DATE = T2.ID_DATE
WHERE 1=1
GROUP BY 1;


-- ¿Cuántos cursos ha tomado el estudiante con más del 80% de las clases vistas?
SELECT
    T2.FIRST_NAME
    ,T2.LAST_NAME
    ,T3.NAME_COURSE
    ,T4.CANT_CLASS AS CLASS_COURSE
    ,COUNT(T1.ID_CLASS) AS CLASS_TAKEN
    ,CASE WHEN CLASS_TAKEN/CLASS_COURSE > 0.8 THEN 1 ELSE 0 END AS FLAG
FROM 
    DWH.FACT_USABILITY T1
    INNER JOIN DWH.DIM_STUDENT T2 ON T1.ID_STUDENT = T2.ID_STUDENT
    INNER JOIN DWH.DIM_CLASS T3 ON T1.ID_CLASS = T3.ID_CLASS
    INNER JOIN (
    	SELECT NAME_COURSE, COUNT(*) AS CANT_CLASS 
    	FROM DWH.DIM_CLASS
    	GROUP BY 1
    ) T4 ON T3.NAME_COURSE = T4.NAME_COURSE
WHERE 1=1
    AND T1.FLAG_COMPLETE = 1
GROUP BY 1,2,3,4
HAVING FLAG = 1;


-- ¿El estudiante ha tenido pausas o cortesías en su suscripción?
SELECT
    T2.FIRST_NAME
    ,T2.LAST_NAME
    ,T3.TYPE_EVENT
    ,COUNT(DISTINCT T1.ID_STUDENT) AS CANT_EVENTS
FROM 
    DWH.FACT_SUBSCRIPTION T1
    INNER JOIN DWH.DIM_STUDENT T2 ON T1.ID_STUDENT = T2.ID_STUDENT
    INNER JOIN DWH.DIM_EVENT T3 ON T1.ID_EVENT = T3.ID_EVENT
WHERE 1=1
    AND T3.TYPE_EVENT IN ('Pausa','Cortesia')
GROUP BY 1,2,3;